class Gallery {
    static getItems() {
        return [
            { id: 1, name: '开学第一天', emoji: '🏫', description: '初中一年级的第一天' },
            { id: 2, name: '新同桌', emoji: '🌸', description: '你们成为了同桌' },
            { id: 3, name: '小学缘分', emoji: '🎒', description: '原来你们在鹤翔小学就是校友' },
            { id: 4, name: '周末夜晚', emoji: '🌙', description: '周末的夜晚，拿起手机' },
            { id: 5, name: '手机告白', emoji: '📱', description: '周末晚上的手机告白' },
            { id: 6, name: '学习为重', emoji: '📚', description: '以学习为重，但心里有些改变' },
            { id: 7, name: '默默陪伴', emoji: '✏️', description: '他耐心地教你做数学题' },
            { id: 8, name: '暑假午后', emoji: '☀️', description: '初一升初二的暑假' },
            { id: 9, name: '折幸运星', emoji: '⭐', description: '和闺蜜们一起折幸运星' },
            { id: 10, name: '热闹夜市', emoji: '🏮', description: '夜市的幸运星摊位开张' },
            { id: 11, name: '摆摊叫卖', emoji: '💰', description: '幸运星大卖' },
            { id: 12, name: '默默守护', emoji: '👀', description: '申玮玮在一旁默默守护' },
            { id: 13, name: '三瓶幸运星', emoji: '✨', description: '他买走三瓶你亲手折的幸运星' },
            { id: 14, name: '中考结束', emoji: '📝', description: '中考顺利结束' },
            { id: 15, name: '高中重逢', emoji: '🏫', description: '同一所高中，不同班级' },
            { id: 16, name: '生日惊喜', emoji: '🎂', description: '生日那天的特别惊喜' },
            { id: 17, name: '无人机礼物', emoji: '🚁', description: '幸运星作为生日礼物送还给你' },
            { id: 18, name: '化学补习', emoji: '🧪', description: '他给你补习化学' },
            { id: 19, name: '高中毕业', emoji: '🎓', description: '高中三年很快过去了' },
            { id: 20, name: '一起返校', emoji: '🚂', description: '他帮你提着行李去学校' },
            { id: 21, name: '到达宿舍', emoji: '🏠', description: '他送你到宿舍' },
            { id: 22, name: '疫情网课', emoji: '💻', description: '虽然相隔，但每天视频' },
            { id: 23, name: '接受告白', emoji: '💕', description: '终于，你们正式在一起了' },
            { id: 24, name: '甜蜜时光', emoji: '🎁', description: '纪念日、生日' },
            { id: 25, name: '美食时光', emoji: '🍲', description: '品尝了很多美食' },
            { id: 26, name: '考下证书', emoji: '📜', description: '他陪着你考下了初级会计证' },
            { id: 27, name: '远方的研究生', emoji: '🌆', description: '相隔两地' },
            { id: 28, name: '异地恋', emoji: '📱', description: '虽然相隔，但感情依然坚定' },
            { id: 29, name: '研究生毕业', emoji: '🎓', description: '研究生毕业了' },
            { id: 30, name: '苏州园林', emoji: '🏯', description: '苏州的美丽园林' },
            { id: 31, name: '南京之旅', emoji: '🏛️', description: '南京的特别之旅' },
            { id: 32, name: '玄武湖求婚', emoji: '💍', description: '夕阳下的求婚' },
            { id: 33, name: '戒指近景', emoji: '💎', description: '闪闪发光的戒指' },
            { id: 34, name: '继续相爱', emoji: '❤️', description: '不急，我们慢慢来' },
            { id: 35, name: '工作日常', emoji: '💼', description: '上班的日子' },
            { id: 36, name: '惊喜投喂', emoji: '🧁', description: '枯燥工作日的甜蜜惊喜' },
            { id: 37, name: '去他家', emoji: '🏡', description: '他邀请你去他家' },
            { id: 38, name: '精心打扮', emoji: '👗', description: '精心打扮，挑选礼物' },
            { id: 39, name: '见他父母', emoji: '👨‍👩‍👦', description: '申妈妈热情地欢迎你' },
            { id: 40, name: '一起吃饭', emoji: '🍲', description: '一桌丰盛的家常菜' },
            { id: 41, name: '端午节回家', emoji: '🐉', description: '端午节一起回家' },
            { id: 42, name: '见你父母', emoji: '👨‍👩‍👧', description: '你的父母也认可了他' },
            { id: 43, name: '永远幸福', emoji: '🌸', description: '要一辈子幸福下去啊！' }
        ];
    }
}
